global:
  nodeSelector: {}
  affinity: {}
  tolerations: {}

replicaCount: 1

metadata:
  labels:
    environment: dev

image:
  repository: infoiplitin
  name: otp-service
  tag: latest

service:
  type: ClusterIP
  port: 80

config:
  WHITELISTED_NUMBERS: ""
  CONNECTION_STRING: "Host=bahmni-dev-postgresql;Port=5432;Username=postgres;Password=welcome;Database=otpservice;"

autoscaling:
  enabled: false

nodeSelector: {}
affinity: {}
tolerations: {}
