apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  whitelisted__numbers:  "{{ .Values.config.WHITELISTED_NUMBERS }}"
  ConnectionStrings__DefaultConnection: "{{ .Values.config.CONNECTION_STRING }}"
  clinic__name:  "{{ .Values.config.CLINIC_NAME }}"