name: master

on:
  push:
    branches:
      - master

env:
  BAHMNI_VERSION: 0.94

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HELM_CHART_PATH: package/helm/
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet core '3.1.100'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.100'
      - name: Build with dotnet
        run: dotnet build otp_service.sln
      - name: Run unit tests
        run: dotnet test otp_service.sln
      - name: Test coverage
        run: dotnet test test/In.ProjectEKA.OtpServiceTest/In.ProjectEKA.OtpServiceTest.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Setting Artifact version
        run: |
          APP_VERSION=$(cat .appversion)
          echo "ARTIFACT_VERSION=$(echo $APP_VERSION-${{github.run_number}})" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: package/docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/otp-service:${{env.ARTIFACT_VERSION}},${{ secrets.DOCKER_USERNAME }}/otp-service
      - name: Helm - Update Version and Image Tag
        run: |
          yq --inplace '.image.tag = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/values.yaml
          yq --inplace '.version = "${{ env.ARTIFACT_VERSION }}"' $HELM_CHART_PATH/Chart.yaml

      - name: Helm Lint
        run: helm lint $HELM_CHART_PATH

      - name: Helm Package
        run: helm package $HELM_CHART_PATH

      - name: Helm - Checkout Charts Repository
        uses: actions/checkout@v2
        with:
          repository: IPLit/helm-charts
          ref: gh-pages
          path: helm-charts
          persist-credentials: false

      - name: Helm - Copy chart
        run: mkdir -p helm-charts/otp-service/ && cp otp-service-${{ env.ARTIFACT_VERSION }}.tgz helm-charts/otp-service/

      - name: Helm - reIndex
        working-directory: helm-charts/
        run: helm repo index --merge index.yaml --url https://IPLit.github.io/helm-charts/  .

      - name: Helm - Publish Chart
        working-directory: helm-charts/
        run: |
          git config user.name ${{ secrets.BAHMNI_USERNAME}}
          git config user.email ${{ secrets.BAHMNI_EMAIL}}
          git add .
          git commit -m "Release of otp-service-${{ env.ARTIFACT_VERSION }}"
          git push 'https://${{secrets.BAHMNI_EMAIL}}:${{secrets.BAHMNI_PAT}}@github.com/IPLit/helm-charts.git' gh-pages
